### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by mckelveygreg** [EugTech/innovate-eugene-web#5]
Do we want to display all of these results on a map? @nohorse 
If so, @johnrnelson , can you geocode addresses (lat, long) and append that to the data?

**Comment by johnrnelson** [comment]
There was [another issue](https://github.com/EugTech/asset-inventory-plan/issues/7) in another [project](https://github.com/EugTech/asset-inventory-plan/) that is similar so maybe we have too many Github projects because its turning out to be a lot to deal with just to do some simple code.

We really only need two projects, the web side and the api side - but to address the question, yeah we **can** geocode the address using the [Google API](https://developers.google.com/maps/documentation/javascript/geocoding) and even a few others but not for free. At least not that I know of. Having said that, this project is hosted on Google so yeah we do have access to any Google API we want and they give the first **X** amount away for free and make it really easy to do so in Node on the server. But in my experience that is really the problem.. it's too easy! Once they have you they don't wanna let go.

"**Just Saying**" so you can't blame me for anything I just said!  :-)

**Comment by mckelveygreg** [comment]
Whoops, good point...
